### ISSUE TITLE
How to verify the effect of this tool?

### ISSUE THREAD

**Issue by liword** [seclab-ucr/INTANG#13]
In past days I learned this tool seems can only work on wordpress.com and dropbox.com.
(which still not working on my machine)
But both this 2 site are forced to use https by now.
Which means if you can access those 2 site as long as you get dns fixed.

So here is the question what is the right way to verify the effect of this tool?
Is this tool suppose to use with http proxy?
Is this tool designed to be a extension to help unencrypted proxy tool to bypass IDS like the GFW?

I'd like to get some answer before spend more time on this.

**Comment by gkso** [comment]
I'd suggest you read our paper. I believe that will answer your questions.
