### ISSUE TITLE
not work on ubuntu:14.04

### ISSUE THREAD

**Issue by yoqu** [seclab-ucr/INTANG#18]
Hello author,thank you the contribute to code. I run the INTANG has some eorr. When I run the `run.sh` shell, the output file will see the error,error log:
```
1510359788.951534 [INFO] Current version: 7
1510359788.952014 [INFO] Starting redis server.
1510359788.960688 [ERROR] failed to set mark on raw socket.
1510359788.960711 [ERROR] Failed to initialize socket module.
```
I don't know How to resolve it, So can you help me ?
My system version is ubunutu:14.04,And run in docker ,The host machine is macos 12.12.

**Comment by gkso** [comment]
Hi, we haven't tested INTANG on macOS or docker. Please try to run it on Linux. :)
