### ISSUE TITLE
Doesn't work under Ubuntu 17

### ISSUE THREAD

**Issue by testcaoy7** [seclab-ucr/INTANG#2]
I ran "run.sh" and get this:
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.

Then, the program exited.

**Comment by lamk** [comment]
same issue

**Comment by gkso** [comment]
Hi, please provide the entire log if possible. I'll look into that. 
By default, logs are located at /var/log/intangd.log

**Comment by liword** [comment]
1509709821.180575 [INFO] Current version: 7
1509709821.180668 [INFO] Starting redis server.
1509709821.186774 [DEBUG] unbinding existing nf_queue handler for AF_INET (if any)
1509709821.187060 [DEBUG] binding nfnetlink_queue as nf_queue handler for AF_INET
1509709821.187353 [DEBUG] binding this socket to queue 1
1509709821.187472 [DEBUG] setting copy_packet mode
1509709821.196843 [DEBUG] Signal 11 recved.
1509709821.197454 [INFO] Saving TTL to redis
1509709821.197495 [DEBUG] 0 records saved.
1509709821.278249 [DEBUG] unbinding from queue 1
1509709821.278593 [DEBUG] closing library handle
1509709821.278800 [INFO] Killing redis server (pid 42402).
1509709821.284620 [INFO] Daemon exited.
