### ISSUE TITLE
Not working on centos7

### ISSUE THREAD

**Issue by SUNFei1126** [seclab-ucr/INTANG#26]
`[root@node2 ~]# curl www.baidu.com
<!DOCTYPE html>
<html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=http://s1.bdstatic.com/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus></span><span class="bg s_btn_wr"><input type=submit id=su value=百度一下 class="bg s_btn"></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=http://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');</script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2017&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>
[root@node2 ~]# curl www.google.com
^C
[root@node2 ~]# curl www.google.com
curl: (7) Failed to connect to 2404:6800:4012::2004: Network is unreachable
[root@node2 ~]# 
` 
test with centos7    run the code  but cannot visit google  is no used  anyone can tell me why

**Comment by chuzirui** [comment]
r u kidding me?


在2018年1月9日 17:58，SUNFei1126<notifications@github.com> 写道：

`[root@node2 ~]# curl www.baidu.com

<title>百度一下，你就知道</title>
新闻hao123地图视频贴吧登录 <script>document.write('登录');</script> 更多产品

关于百度About Baidu

©2017 Baidu 使用百度前必读  意见反馈 京ICP证030173号 

[root@node2 ~]# curl www.google.com
^C
[root@node2 ~]# curl www.google.com
curl: (7) Failed to connect to 2404:6800:4012::2004: Network is unreachable
[root@node2 ~]#
`
test with centos7 run the code but cannot visit google is no used anyone can tell me why

**Comment by LuoZijun** [comment]
@chuzirui hhhh

**Comment by SUNFei1126** [comment]
@chuzirui What do you mean

**Comment by paperbag** [comment]
https://github.com/seclab-ucr/INTANG/issues/4#issuecomment-341669683

PLEASE SEARCH IT BEFORE ASKED.
