### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mengzhongshuike** [seclab-ucr/INTANG#3]
gcc -g -c  -I. -Istrategies  main.c -o main.o -pthread
gcc -g -c  -I. -Istrategies  helper.c -o helper.o -pthread
gcc -g -c  -I. -Istrategies  logging.c -o logging.o -pthread
gcc -g -c  -I. -Istrategies  socket.c -o socket.o -pthread
gcc -g -c  -I. -Istrategies  strategy.c -o strategy.o -pthread
strategy.c: In function 'dump_strat_weights':
strategy.c:501:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < g_strat_num; i++) {
     ^
strategy.c:501:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [strategy.o] Error 1
make[1]: Leaving directory `/root/INTANG/src'
make: *** [all] Error 2

**Comment by Justsoos** [comment]
same problem too, what is your trick?
