### ISSUE TITLE
INTANG doesn't work at all on arch linux

### ISSUE THREAD

**Issue by 20NE** [seclab-ucr/INTANG#38]
I give INTANG a second try, this time, installation is fine, running is fine, but just doesn't work:
sensitive websites still reset, which are not banned by IP address, I'm sure, and I do as FAQ.md: 

> connecting the website again later after a certain period (i.e. 90 seconds). INTANG will automatically choose the best strategy for each server based on historical results
 
still no luck.

**Comment by gkso** [comment]
Have you tried ./run.sh 6.
And have you checked the log to see what happened?

**Comment by 20NE** [comment]
I've not tried no.6 strategy, but I've tried several other strategies.
no error or anything special in log

**Comment by 20NE** [comment]
I'll be damn, INTANG works now.
I reinstall INTANG, now it works.
